### PR TITLE
Fix for #230

### PR DESCRIPTION
**Pull request by jdidion**
In a `V2Runtime`, the `get` method is currently trying to coerce to the intersection of the allowed and destination types. For `memory` (and maybe others) there is a problem - the allowed types are `[T_String, T_Int]` but the dest type is `[T_Int]`, so the intersection is `[T_Int]` and coercion from `T_String` throws an exception. What you need to do instead is first evaluate the expression to one of the allowed types, then coerce to the destination type, which is what is implemented in this PR.

### CODE REVIEW

**Review by Gvaihir — CHANGES_REQUESTED** [review]
please commit `bug_230.wdl`

**Comment by jdidion** [comment]
Sorry, just added it

**Review by Gvaihir — APPROVED** [review]
Thanks, I will keep an eye on dxC regressions

**Comment by commandlinegirl** [comment]
This is now released in https://github.com/dnanexus/dxCompiler/releases/tag/2.10.6 cc @jdidion - thank you!

**Pull request merged**
