### PR TITLE
Source Text in AST

### PR DESCRIPTION
**Pull request by orodeh**
This branch adds pointers to the source text in each of the nodes in the abstract syntax tree.

### CODE REVIEW

**Comment by orodeh** [comment]
@jdidion The code doesn't compile now, which you can see because there is a little red `x` in the front page. The issue is mostly this:

```
ROORT/wdlTools/src/main/scala/wdlTools/generators/SspRenderer.scala:3:12: object fusesource is not a member of package org
[error] import org.fusesource.scalate.TemplateEngine
```

What should I add to the build.sbt?

**Comment by orodeh** [comment]
@jdidion I added this line:
```
addSbtPlugin("org.scalatra.scalate" % "sbt-scalate-precompiler" % "1.9.1.0")
```

to file `project/plugins.sbt`. It may be in your `.gitignore` list, which is why the modification didn't make it to master branch. I don't know if this is the correct version for this library, but at least it makes my code compile.

Another issue is unit tests which do not compile. I think this stems from a change I made where the parser requires a URL, and not string textual code. This allows reporting errors as line/column/file-name. In the code there are many cases where we were calling with parser with a string, instead of a URL. I have changed my test cases and my code, but I am not sure how to do the same for your code.

**Comment by jdidion** [comment]
It compiles now.

**Comment by jdidion** [comment]
Test work now.

**Comment by orodeh** [comment]
Great, I everything works now!

**Pull request merged**
